#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Nov 1, 2014
@author: daniel

Toy Remote EXecution Server Command-Line Interface

Usage:
    server <config_file> [--ssl <keyfile> <certfile>]
"""
from configparser import ConfigParser
import logging
from docopt import docopt
from trex import TrexServer, TrexConfig, TrexAuthMgr


DEFAULT_LOGFILE = 'server.log'
DEFAULT_LOGLEVEL = logging.INFO
DEFAULT_LOGFORMAT = '%(asctime)-15s %(message)s'

logging.basicConfig(filename=DEFAULT_LOGFILE,
                    level=DEFAULT_LOGLEVEL,
                    format=DEFAULT_LOGFORMAT)

if __name__ == '__main__':  
    args = docopt(__doc__)
    logging.info("Starting server with args: {}".format(args))
    cfgparser = ConfigParser()
    cfgparser.read(args['<config_file>'])
    config = TrexConfig(cfgparser)
    authmgr = TrexAuthMgr(config)
    s = TrexServer(config, authmgr, keyfile=args['<keyfile>'],
                   certfile=args['<certfile>'])
    s.serve_forever()
